### ISSUE TITLE
Protocol not properly obtained from req.protocol

### ISSUE THREAD

**Issue by jsdw** [OptimalBits/Crawlme#2]
In crawme.js (starting line 30) you have the following:

var protocol = req.protocol || options.protocol;
var url =  options.protocol + '://' + req.headers.host;

that second options.protocol should just be protocol, otherwise the above line is useless :)

**Comment by arokor** [comment]
Correct. Has been fixed now
Cheers
Aron

On Thu, Mar 7, 2013 at 4:03 PM, lytnus notifications@github.com wrote:

> In crawme.js (starting line 30) you have the following:
> 
> var protocol = req.protocol || options.protocol;
> var url = options.protocol + '://' + req.headers.host;
> 
> that second options.protocol should just be protocol, otherwise the above
> line is useless :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/OptimalBits/Crawlme/issues/2
> .

## 

_Aron Kornhall_
